# User tier configuration
# This file defines user behavior parameters
# for each customer tier.

default_tiers: &default_tiers
    # Chance user will visit at least once a month (0–1)
    monthly_visit_chance: 4

    # Multiplier applied to the number of visits per month
    monthly_visit_multiplier: 1
    
tiers:
    # ---------------------------------------
    # Tier 1 — Highest value customers
    # Bulk buyers who spend heavily each month.
    # ---------------------------------------
    - id: 1
      label: "High spenders & bulk buyers"

      # Chance user will visit at least once a month (0–1)
      monthly_visit_chance: 0.9

      # Multiplier applied to the number of visits per month
      monthly_visit_multiplier: 1

      # Funnel conversion rates (the number represents the probability of moving from the current step to the next)
      conversion_rate:
          landing_page: 0.7
          product_view: 0.8
          add_to_cart: 0.9
          checkout: 0.8
          paid: 1

      # Probability distribution over product categories
      product_preferences:
          electronics: 0.4
          fashion: 0.3
          grocery: 0.2
          books: 0.1


    # ---------------------------------------
    # Tier 2 — High spend, frequent visitors
    # Spend consistently and browse often.
    # ---------------------------------------
    - id: 2
      label: "High spenders & frequent visitors"
      monthly_visit_chance: 0.9
      monthly_visit_multiplier: 1
      monthly_spend_multiplier: 4

      product_preferences:
          electronics: 0.4
          fashion: 0.3
          grocery: 0.2
          books: 0.1


    # ---------------------------------------
    # Tier 3 — Medium spenders with moderate activity
    # ---------------------------------------
    - id: 3
      label: "Medium spenders & occasional visitors"
      monthly_visit_chance: 0.9
      monthly_visit_multiplier: 1
      monthly_spend_multiplier: 3

      product_preferences:
          electronics: 0.4
          fashion: 0.3
          grocery: 0.2
          books: 0.1


    # ---------------------------------------
    # Tier 4 — Low-value buyers
    # Buy rarely and mostly random items.
    # ---------------------------------------
    - id: 4
      label: "Low spenders & miscellaneous buyers"
      monthly_visit_chance: 0.9
      monthly_visit_multiplier: 1

      # Lower average spend but occasionally spike (multiplier)
      monthly_spend_multiplier: 7

      product_preferences:
          electronics: 0.4
          fashion: 0.3
          grocery: 0.2
          books: 0.1
